version: '3.8'

services:
  sql-chat-bot:
    image: sql-chat-bot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app